server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service-route
              uri: lb://AuthServiceConfig
              predicates:
                - Path=/api/auth/**

            - id: repository-service-route
              uri: lb://RepoConfig
              predicates:
                - Path=/api/repositories/**

            - id: cicd-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/cicd/**
              filters:
                - StripPrefix=2

            - id: code-review-service-route
              uri: lb://CodeReviewConfig
              predicates:
                - Path=/api/reviews/**

            - id: chat-service-route
              uri: lb://ChatServiceConfig
              predicates:
                - Path=/api/chat/**
              filters:
                - StripPrefix=2

            - id: analytics-service-route
              uri: lb://AnalyticsConfig
              predicates:
                - Path=/api/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000