server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devflow_db
    username: devflow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  avatar-bucket-name: devflow-avatars

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh-expiration: 604800000