server:
  port: 8085

spring:
  application:
    name: code-review-service

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/code_review_db
    username: devflow
    password: password
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: code-review-group

# Eureka Service Discovery Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true